# setup
language: generic
sudo: required
services:
  - docker

# commands to run before deploy / test
defore_install:
  #  build docker image
  - docker build -f Dockerfile.dev -t tamplier2911/docker-cra-travis .

# command to run tests suite
script:
  #  create and run a container out of image
  #  set environment variable CI to true
  #  re-write startup command to run test suite
  - docker run -e CI=true tamplier2911/docker-cra-travis npm run test
